cmake_minimum_required(VERSION 3.10.1)

### ----- Generate dynamics for pendulum ----- ###
project(pendulum) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for double pendulum ----- ###
project(double_pendulum) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for cartpole ----- ###
project(cartpole) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for double cartpole ----- ###
project(double_cartpole) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for uniform rigidbody ----- ###
project(rigidbody) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for quadrotor ----- ###
project(quadrotor) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Unitree Go1 ----- ###
project(unitree_go1) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Unitree Go2 ----- ###
project(unitree_go2) # Change this for each model

set(DIR models/${PROJECT_NAME}/generated_code/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 1 contact point per foot ----- ###
project(nadia_simple_1cp) # Change this for each model

set(DIR models/nadia/generated_code/simple_1cp/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 4 contact point per foot ----- ###
project(nadia_simple_4cp) # Change this for each model

set(DIR models/nadia/generated_code/simple_4cp/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 1 contact point per foot with quat orientation ----- ###
project(nadia_simple_1cp_quat) # Change this for each model

set(DIR models/nadia/generated_code/simple_1cp_quat/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 1 contact point per foot with axis angle orientation ----- ###
project(nadia_simple_1cp_aa) # Change this for each model

set(DIR models/nadia/generated_code/simple_1cp_aa/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 1 contact point per foot with axis angle orientation ----- ###
project(nadia_simple_1cp_aa_no_arms) # Change this for each model

set(DIR models/nadia/generated_code/simple_1cp_aa_no_arms/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 4 contact point per foot, no arms ----- ###
project(nadia_simple_4cp_no_arms) # Change this for each model

set(DIR models/nadia/generated_code/simple_4cp_no_arms/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Nadia simple knee 4 contact point per foot, no arms ----- ###
project(nadia_simple_4cp_no_arms_spine) # Change this for each model

set(DIR models/nadia/generated_code/simple_4cp_no_arms_spine/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Pineapple v0 ----- ###
project(pineapple_v0) # Change this for each model

set(DIR models/pineapple/generated_code/pineapple_v0/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Pineapple v0 Quaternion Kinematics ----- ###
project(pineapple_quat_v0) # Change this for each model

set(DIR models/pineapple/generated_code/pineapple_quat_v0/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Pineapple v1 ----- ###
project(pineapple_v1) # Change this for each model

set(DIR models/pineapple/generated_code/pineapple_v1/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Pineapple v1 Quaternion Kinematics ----- ###
project(pineapple_quat_v1) # Change this for each model

set(DIR models/pineapple/generated_code/pineapple_quat_v1/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Pineapple v2 ----- ###
project(pineapple_v2) # Change this for each model

set(DIR models/pineapple/generated_code/pineapple_v2/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for Pineapple v2 Quaternion Kinematics ----- ###
project(pineapple_quat_v2) # Change this for each model

set(DIR models/pineapple/generated_code/pineapple_quat_v2/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c") 

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})

### ----- Generate dynamics for G7 OpenArm Quaternion Kinematics ----- ###
project(g7_openarm_quat) # Change this for each model

set(DIR models/g7_openarm/generated_code/g7_openarm_quat/) # Change if not the default

include_directories(${DIR})

file(GLOB SOURCES "${DIR}*.c")

add_library(${PROJECT_NAME} SHARED src/wrapper.c ${SOURCES})
