/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dynamics_alloc_mem(void);
int dynamics_init_mem(int mem);
void dynamics_free_mem(int mem);
int dynamics_checkout(void);
void dynamics_release(int mem);
void dynamics_incref(void);
void dynamics_decref(void);
casadi_int dynamics_n_in(void);
casadi_int dynamics_n_out(void);
casadi_real dynamics_default_in(casadi_int i);
const char* dynamics_name_in(casadi_int i);
const char* dynamics_name_out(casadi_int i);
const casadi_int* dynamics_sparsity_in(casadi_int i);
const casadi_int* dynamics_sparsity_out(casadi_int i);
int dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dynamics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dynamics_SZ_ARG 2
#define dynamics_SZ_RES 1
#define dynamics_SZ_IW 0
#define dynamics_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
