/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int inverse_dynamics_deriv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int inverse_dynamics_deriv_alloc_mem(void);
int inverse_dynamics_deriv_init_mem(int mem);
void inverse_dynamics_deriv_free_mem(int mem);
int inverse_dynamics_deriv_checkout(void);
void inverse_dynamics_deriv_release(int mem);
void inverse_dynamics_deriv_incref(void);
void inverse_dynamics_deriv_decref(void);
casadi_int inverse_dynamics_deriv_n_in(void);
casadi_int inverse_dynamics_deriv_n_out(void);
casadi_real inverse_dynamics_deriv_default_in(casadi_int i);
const char* inverse_dynamics_deriv_name_in(casadi_int i);
const char* inverse_dynamics_deriv_name_out(casadi_int i);
const casadi_int* inverse_dynamics_deriv_sparsity_in(casadi_int i);
const casadi_int* inverse_dynamics_deriv_sparsity_out(casadi_int i);
int inverse_dynamics_deriv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int inverse_dynamics_deriv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define inverse_dynamics_deriv_SZ_ARG 2
#define inverse_dynamics_deriv_SZ_RES 2
#define inverse_dynamics_deriv_SZ_IW 0
#define inverse_dynamics_deriv_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
