/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int kinematics_force_hvp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int kinematics_force_hvp_alloc_mem(void);
int kinematics_force_hvp_init_mem(int mem);
void kinematics_force_hvp_free_mem(int mem);
int kinematics_force_hvp_checkout(void);
void kinematics_force_hvp_release(int mem);
void kinematics_force_hvp_incref(void);
void kinematics_force_hvp_decref(void);
casadi_int kinematics_force_hvp_n_in(void);
casadi_int kinematics_force_hvp_n_out(void);
casadi_real kinematics_force_hvp_default_in(casadi_int i);
const char* kinematics_force_hvp_name_in(casadi_int i);
const char* kinematics_force_hvp_name_out(casadi_int i);
const casadi_int* kinematics_force_hvp_sparsity_in(casadi_int i);
const casadi_int* kinematics_force_hvp_sparsity_out(casadi_int i);
int kinematics_force_hvp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int kinematics_force_hvp_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define kinematics_force_hvp_SZ_ARG 3
#define kinematics_force_hvp_SZ_RES 2
#define kinematics_force_hvp_SZ_IW 0
#define kinematics_force_hvp_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
