/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int kinematics_jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int kinematics_jacobian_alloc_mem(void);
int kinematics_jacobian_init_mem(int mem);
void kinematics_jacobian_free_mem(int mem);
int kinematics_jacobian_checkout(void);
void kinematics_jacobian_release(int mem);
void kinematics_jacobian_incref(void);
void kinematics_jacobian_decref(void);
casadi_int kinematics_jacobian_n_in(void);
casadi_int kinematics_jacobian_n_out(void);
casadi_real kinematics_jacobian_default_in(casadi_int i);
const char* kinematics_jacobian_name_in(casadi_int i);
const char* kinematics_jacobian_name_out(casadi_int i);
const casadi_int* kinematics_jacobian_sparsity_in(casadi_int i);
const casadi_int* kinematics_jacobian_sparsity_out(casadi_int i);
int kinematics_jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int kinematics_jacobian_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define kinematics_jacobian_SZ_ARG 1
#define kinematics_jacobian_SZ_RES 1
#define kinematics_jacobian_SZ_IW 0
#define kinematics_jacobian_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
