/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int velocity_kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int velocity_kinematics_alloc_mem(void);
int velocity_kinematics_init_mem(int mem);
void velocity_kinematics_free_mem(int mem);
int velocity_kinematics_checkout(void);
void velocity_kinematics_release(int mem);
void velocity_kinematics_incref(void);
void velocity_kinematics_decref(void);
casadi_int velocity_kinematics_n_in(void);
casadi_int velocity_kinematics_n_out(void);
casadi_real velocity_kinematics_default_in(casadi_int i);
const char* velocity_kinematics_name_in(casadi_int i);
const char* velocity_kinematics_name_out(casadi_int i);
const casadi_int* velocity_kinematics_sparsity_in(casadi_int i);
const casadi_int* velocity_kinematics_sparsity_out(casadi_int i);
int velocity_kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int velocity_kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define velocity_kinematics_SZ_ARG 1
#define velocity_kinematics_SZ_RES 1
#define velocity_kinematics_SZ_IW 0
#define velocity_kinematics_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
